-- Archivo sin uso — la función de personajes/avatares fue eliminada.
-- La columna players.avatar ya NO es necesaria. Puedes borrar este archivo.
-- (Si ya habías creado la columna, puedes dejarla o quitarla con:
--   ALTER TABLE players DROP COLUMN IF EXISTS avatar; )
